name: Version Management

on:
  push:
    branches:
      - 'release-*'  # This will trigger only on pushes to release branches

jobs:
  update-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Get the version
      id: get_version
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        VERSION=${BRANCH_NAME#release-}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Update version file
      run: |
        if [ ! -f VERSION ] || [ "$(cat VERSION)" != "${{ steps.get_version.outputs.VERSION }}" ]; then
          echo ${{ steps.get_version.outputs.VERSION }} > VERSION
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION
          git commit -m "Bump version to ${{ steps.get_version.outputs.VERSION }}"
          git push
          echo "Version file updated to ${{ steps.get_version.outputs.VERSION }}"
        else
          echo "Version file already up to date with ${{ steps.get_version.outputs.VERSION }}"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}